# Generated by Django 5.0.1 on 2024-01-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, upload_to='photos/brand_image'),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='photos/cat_image'),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='photos/product_image'),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='thumbnail_image',
            field=models.ImageField(upload_to='photos/product_thumbnail'),
        ),
    ]
