# Generated by Django 5.0.1 on 2024-01-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_brand_image_category_cat_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='product_image',
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='photos/product_thumbnail'),
        ),
        migrations.CreateModel(
            name='Additional_Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/product_additional')),
                ('is_active', models.BooleanField(default=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_product_images', to='products.product_variant')),
            ],
        ),
    ]
