# Generated by Django 5.0.1 on 2024-01-30 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_variant_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atribute_value',
            old_name='atribute_value',
            new_name='Atribute_value',
        ),
        migrations.AddField(
            model_name='product_variant',
            name='variant_name',
            field=models.CharField(blank=True, default='d', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_catg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cate', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
    ]
