# Generated by Django 5.0.1 on 2024-01-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_variant_variant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atribute_value',
            old_name='Atribute_value',
            new_name='atribute_value',
        ),
    ]
