# Generated by Django 5.0.1 on 2024-02-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_croppedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CroppedImage',
        ),
    ]
