# Generated by Django 5.0.1 on 2024-02-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_image_imagefk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefk',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageFK',
        ),
    ]
