# Generated by Django 5.0.1 on 2024-03-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_coupon_usercoupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_percentage',
            new_name='discount',
        ),
    ]
