# Generated by Django 5.0.1 on 2024-03-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_discount_percentage_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default=0, upload_to='photos/product_thumbnail'),
        ),
    ]
