# Generated by Django 5.0.1 on 2024-03-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_variant_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='offer',
        ),
    ]
