# Generated by Django 5.0.1 on 2024-02-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderproduct_order_status_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled Admin', 'Cancelled Admin'), ('Cancelled User', 'Cancelled User'), ('Returned', 'Returned')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Cancelled_Admin', 'Cancelled Admin'), ('Cancelled_User', 'Cancelled User'), ('Returned_User', 'Returned User'), ('Return_pending', 'Returned pending')], default='New', max_length=20),
        ),
    ]
