# Generated by Django 5.0.1 on 2024-02-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderproduct_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Cancelled_Admin', 'Cancelled Admin'), ('Cancelled_User', 'Cancelled User'), ('Returned', 'Returned'), ('Return Status', 'Returned Status'), ('Return Approved', 'Returned Approved'), ('Return Rejected', 'Returned Rejected')], default='New', max_length=20),
        ),
    ]
