# Generated by Django 5.0.1 on 2024-02-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderproduct_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
