# Generated by Django 5.0.1 on 2024-03-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderproduct_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='wallet_discount',
            new_name='grand_total',
        ),
    ]
