# Generated by Django 5.0.1 on 2024-03-04 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_coupon'),
        ('products', '0015_rename_discount_percentage_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.usercoupon'),
        ),
    ]
