# Generated by Django 5.0.1 on 2024-02-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_adressbook_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressbook',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
