# Generated by Django 5.0.1 on 2024-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0002_referraloffer_referraluser'),
        ('products', '0016_product_variant_offer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('product_offer_slug', models.SlugField(max_length=200, unique=True)),
                ('product_offer_image', models.ImageField(blank=True, upload_to='media/product_offer/')),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(related_name='product_offers', to='products.product')),
            ],
        ),
    ]
