# Generated by Django 5.0.1 on 2024-03-10 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0003_productoffer'),
        ('products', '0016_product_variant_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='products',
        ),
        migrations.AddField(
            model_name='productoffer',
            name='products',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='products.product'),
            preserve_default=False,
        ),
    ]
