# Generated by Django 5.0.1 on 2024-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='banners/')),
                ('image2', models.ImageField(upload_to='banners/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotion_banners/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
