# Generated by Django 5.0.1 on 2024-03-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionbanner',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='title2',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='title3',
            field=models.CharField(default='dd', max_length=100),
            preserve_default=False,
        ),
    ]
